sudo : required
services :
  - docker


before_install :
  - docker build -t tusharpaliwal/docker-react -f Dockerfile.dev .
  
script:
  - docker run  tusharpaliwal/docker-react npm run test -- --converage 
